language: php

sudo: required

php:
  - 7.0
  - 7.1

env:
  global:
    - setup=basic
    - coverage=no

before_install:
  - travis_retry composer self-update
  - composer config discard-changes true
  - sudo apt-get remove -y imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -y libtiff-dev libjpeg-dev libdjvulibre-dev libwmf-dev pkg-config liblcms2-dev
  - sh ./tests/travis/imagick.sh
  - phpenv rehash

before_script:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-source --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-lowest --prefer-stable; fi
  - if [[ $setup = 'coveralls' ]]; then travis_retry composer require "psr/log=1.0.0" "satooshi/php-coveralls=~0.6" --prefer-source --no-interaction --dev; fi

script:
  - if [[ $coverage = 'yes' ]]; then ./vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml; fi
  - if [[ $coverage = 'no' ]]; then ./vendor/bin/phpunit -c phpunit.xml; fi

after_script:
  - if [[ $setup = 'coveralls' ]]; then php vendor/bin/coveralls -v; fi

matrix:
  include:
    - php: 7.0
      env: setup=lowest
    - php: 7.0
      env: setup=stable
    - php: 7.0
      env: setup=coveralls coverage=yes
  allow_failures:
    - env: setup=stable
    - env: setup=coveralls coverage=yes
  fast_finish: true
